# Generated by Django 5.2.4 on 2025-07-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('scheme', models.CharField(choices=[('I', 'Scheme I'), ('K', 'Scheme K')], max_length=1)),
                ('year', models.IntegerField()),
                ('pdf', models.FileField(upload_to='papers_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='syllabus_pdfs/')),
            ],
        ),
    ]
